### PR TITLE
Update bot version to 11996

### PR DESCRIPTION
**Pull request by ron-murhammer**

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, I'm gonna merge it here in a few minutes and jump into the lobby to see what happens :)

**Comment by ssoloff** [comment]
@ron-murhammer Derp.  Just noticed this updated the prod lobby version, not the bots.

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, appears the lobby restarted. Though there aren't any bots now...

**Comment by ron-murhammer** [comment]
Yeah, letting it hit the next 5 min mark and if nothing joins then I'm gonna login and try manually restarting the bots.

**Pull request merged**
