### PR TITLE
Add nginx config file

### PR DESCRIPTION
**Pull request by RoiEXLab**
As discussed in https://github.com/triplea-game/dice-server/pull/49

### CODE REVIEW

**Comment by ssoloff** [comment]
@RoiEXLab I applied the new configuration at 2018-08-20T17:00 UTC.  I re-ran the Qualys test shortly thereafter (after clearing their cache).  It still states that TLS 1.0 is supported.  Not sure why the configuration didn't take.

**Comment by ssoloff** [comment]
This was in the log:

```
Aug 20 13:01:44 tripleawarclub nginx[20068]: nginx: [warn] duplicate value "TLSv1.1" in /etc/nginx/conf.d/nginx.conf:4
Aug 20 13:01:44 tripleawarclub nginx[20068]: nginx: [warn] duplicate value "TLSv1.2" in /etc/nginx/conf.d/nginx.conf:4
```

I'm guessing that setting the `ssl_protocols` directive a second time doesn't clear out the old values.

**Comment by RoiEXLab** [comment]
@ssoloff Hmm not sure what to do about this. Not sure if we really should fiddle around with the config

**Comment by ssoloff** [comment]
Yeah, if there's no way to override an existing parameter, we have to go back to adding _/etc/nginx/nginx.conf_ to source control and editing it directly.

**Pull request merged**
