### PR TITLE
Update root_user_authorized_keys

### PR DESCRIPTION
**Pull request by prastle**
Add my root from admin ssh

### CODE REVIEW

**Comment by DanVanAtta** [comment]
With respect I'm not sure I agree on this @prastle; at the very least this is a step in the wrong direction as 'root' should be reserved for correction of scripting errors only, absolute necessity. The infrastructure install scripts run as root, as commands needed as root should be run there. Hence needing to run a command as root, and not being able to add a scripted line for it should pretty much an incredible exception, perhaps a bit more common as we break in the infrastructure, but after a month or two from now I expect us to never see root logins.

**Comment by prastle** [comment]
@DanVanAtta Ok so how am I supposed to fix the broken bots?  Since no one has yet?

**Comment by RoiEXLab** [comment]
@prastle I think what he's trying to say is that you shouldn't even have to fix the bots, because ideally the problems that occur should either fix themselves by restarting, or by shutting them down if too many are active.

What are the current problems? 
What would you do to fix them?

**Comment by prastle** [comment]
@RoiEXLab If you look at the lobby you will see that three servers have one or more bots missing.

**Comment by prastle** [comment]
@RoiEXLab so are you saying the only fix no is rebooting those servers from Linode and shutting any extra bots that appear whenever this happens and a bot does not relaunch?  Which I will remind you we did yesterday.  Thus why are 4-5 (without counting atm) bots missing from three diff servers?

**Comment by prastle** [comment]
@DanVanAtta  apparently I have never been clear enough so i will try to explain as @RoiEXLab  pointed out since you both think the bot's magically work!  They lock up daily and sometimes hourly.  Generally it just needs a reset.  With the removal of Roi's scipts etc you guy's removed all that knew how to reset.  I guess from now on you guys can either A! empty a server of players and reboot it from linode or B! allow us to reboot bots individually.  I assume this occurs from multiple players playing old engines or bad isp.  Either way often we have ghost bots with ghost players as well as bots that don't return "Magically".  So i would sug we allow admin to at least be able to restart bots.  If your worried about root.  Either way atm 3 ghost bots and 4 missing bots more are coming.  So UNLESS yourself and Roi want to watch the lobby we need a fix here...  NP with me I can host ;) up to you.
  But since the lobby was down 12 hrs and bots more ... I sug you allow others to fix since you guys are too busy at times with a months notice of linode shutdown.   Done my vent do what ya wish.  Either way if only three peeps have root with your current setup I guess those three peeps they need to be available.

**Comment by Heppisorus** [comment]
Does seem problematic that the online guy(s) with the wherewithal to fix things in real time as they develop... can no longer help to keep the Lobby running smoothly as issues arise.

**Comment by prastle** [comment]
I should also add in the future please don't remove my ssh access without at least telling me.  Either way gl but its quite detailed in your pr.  I kinda feel stupid spending 3 hrs trying to fix to discover that every bot server you removed me from.  Np fix yourselves.

**Comment by RoiEXLab** [comment]
@prastle Technically your access was never removed. 
The bot servers were just removed and retreated, your access on all the other servers should still be the same on all the other servers AFAIK

**Comment by DanVanAtta** [comment]
Let's not jump to hyperbole.

`admin` use should have all the access you need @prastle , if it does not, you must let us know so we can fix it.

With respect to bots every day, that is a problem. We *now* have more capacity and I think can start dealing with that.

My original point is that `root` is the ultra-super-user account and NOBODY should be using it unless there is a real emergency (there simply should not be any reason as the infrastructure scripts are *the* way to do modifications, otherwise admin can do all the day-to-day restarts and (soon) checking of logs.

**Comment by DanVanAtta** [comment]
PS: even in an emergency, logging in as root should still not be necessary, as the infrastructure scripts are *the* way to modify the server. At this point nobody should even be logging in to servers ever (unless we have some persistent crash problems, which we need to fix).

The fixing of bots quietly and daily is useful to keep them running, but until we start investigating the problem we'll be doing that forever. Meanwhile, likely a one to two hour effort is enough to fix any one problem, i'd be surprised if the bots had more than 2 or 3 ongoing problems. 

So if bots are crashing, and needing restart, we need to know - particularly so we can look at it and the logs. The logs are *gone* after 3 days, so we do need to know.

**Comment by DanVanAtta** [comment]
> So i would sug we allow admin to at least be able to restart bots

Admin user should be able to do this, the peeps with root should never be using it. The root access is copied to all other users, so we should all be using admin.

**Comment by prastle** [comment]
Cool what's the script to be run in admin?  And to be clear the bots have been doing this  since they were created so how is this news?

**Comment by RoiEXLab** [comment]
@prastle The lobby thing was a problem eith network related configuration files, probably caused by a bad removal of a package.
I'm guessing similar problems have occurred for other folks as well. Thus why ifuodown, the networking tools that were used for centuries were replaced in the latest ubuntu version, so that problem should hopefully no longer occur in the future when we upgrade our ubuntu in a year or something (not supported earlier).
Looking back I didn't have to add myself as root, but I didn't know how to prevent a fith bot from starting in an automated manner (for some reason not all servers had a fith bot enabled), I'm still not entirely sure how to implement it, but I think I found a way and so this issue is being tracked in #42, clearly a misconfiguration issue we should've thought of earlier.
The scripts should still be the same.
At which point are they failing for you?

**Comment by prastle** [comment]
@RoiEXLab  All the basic commands. They fail as admin.  Try it yourself as admin.

Admin - (read-only + can restart lobby and bots) access

BASIC Commands - These are commands in listed below in bold black. You must be logged in as “admin” user to run all the following commands.

Is incorrect or I would have stopped the extra bots that night.  As you already stated
"but I didn't know how to prevent a fith bot from starting in an automated manner (for some reason not all servers had a fith bot enabled)"

**Comment by RoiEXLab** [comment]
@prastle ok, dug into this a little bit deeper, and there seem to be a couple of problems:
#### `cd maps` won't work
The reason is pretty straightforward, you are no longer loggin in as triplea user, but the bots are still being executed as that user, so the maps folder is still on `/home/triplea/maps`, while you try to implicitly cd into `/home/admin/maps` (`/home/<username>` is the default directory when logging in).
This shouldn't be a problem though, as the maps should update themselves automatically.
However if you whish to manually add a beta map that's not already in the official map pool, that won't work because the admin user shouldn't have the permission to change files in the maps directory.
But I think I can speak for @DanVanAtta that we shouldn't support unofficial maps on official bots in the current state of the engine, at least the complete ecosystem isn't designed to have unofficial maps
#### `sudo service triplea-bot@<number> stop|start|status` won't work
Obviously the first 2 command attempts have the wrong syntax, we write `<number>` to make clear you shouldn't write literally `number` instead of an actual number in the command.
However The 3rd command attempt wouldn't work either, because since this repo exists, a leading 0 digit was added to the bot numbers, therefore the bots are now 2-01 and 2-02 instead of 2-1 and 2-2 etc.
So you'd need to run `sudo service triplea-bot@01 stop` to have everything working.
~BUT the admin user isn't allowed to for some weird reason, the following lines should allow all commands:~
https://github.com/triplea-game/infrastructure/blob/20080d0b170f0af60b9962a5df370ec4a8dee928/root/tasks/admin_user.sh#L20-L22

But looking at `/etc/sudoers` revealed that currently only the restart command is supported.

UPDATE: Looked at the code again, found the issue. We're checking if a `triplea-bot@<number>` line exists, of course it exists when we're adding the restart permission, will fix soon (today, in a couple of hours probably)

##### Off topic
For me when logging in as admin the ls command behaved super weirdly, sometimes the convinience scripts were shown, sometimes nothing, not even the current directory was shown.
I suspect this has something to do with the overall memory usage, but still, this shouldn't be the case.
@prastle Keep an eye on #40 @DanVanAtta created some wrapper scripts in `/home/admin`, so you'd have to execute `./restart_bot_<number>` and `./start_all`, `./stop_all` `./restart_all` etc. instead of remebering the actual commands. Using TAB there's no potential for typos 😉 
For a list of all commands, you can run `ls -lah` when logging in.

**Comment by prastle** [comment]
does tab replace up arrow? since up arrow is broken as well on relogin?

**Comment by RoiEXLab** [comment]
@prastle Does arrow up just not do anything, or are weird characters appearing? Something like ^A] or something

**Comment by prastle** [comment]
does nothing

**Comment by RoiEXLab** [comment]
Seems like a good option.

**Comment by RoiEXLab** [comment]
@prastle Your SSH password doesn't matter.
When everything works you won't be prompted for one, because there is none.

**Comment by prastle** [comment]
Oh so everything is broken but took a week to argue about it ? :) k thanks for finally confirming...  Gl bro

**Comment by RoiEXLab** [comment]
@prastle 
Yup, seems like it
#46
You should be able to access bots in <5mins
I was test restarting the 201 bot earlier, might be your magically restarting bot ^^

**Comment by prastle** [comment]
Nope i was reffering to bot 401

**Comment by RoiEXLab** [comment]
Issue should be resolved

**Comment by prastle** [comment]
nope Atlanta doesn't work

**Comment by RoiEXLab** [comment]
But all others do?

**Comment by prastle** [comment]
up arrow broken etc

**Comment by prastle** [comment]
no matter when they all lock up fix yourselves
two of you have root hope your awake next time a months notice occurs of linode reboot

**Comment by prastle** [comment]
close all my issues
fix yourselves

**Comment by RoiEXLab** [comment]
@prastle I meant that you should be able to start and stop the bots on all the servers now...

**Comment by prastle** [comment]
AND I MEANT that until you add some mods ssh (your new changes mean even if they work?) WHICH THEY DO NOT!)  ATM 2 OF YOU CAN FIX IT!  either way atm your fix fails for Atlanta

**Comment by prastle** [comment]
done argument
a week of bullshit with a months notice..

**Comment by prastle** [comment]
Ok ty.  It is just sad that it took a week with a months notice.  Either way it does not change the problem you guys have introduced.  Hopefully some other mods will apply for your ssh.  GOOD LUCK!

**Comment by prastle** [comment]
@DanVanAtta  I agree that I lost my temper.  So I apologize to all.  To clarify tho.  Linode informed us of the shutdown and reboot a month in advance.  All devs where afk when it occurred.  I logged in at three am and could do nothing since my root had been removed. The lobby was down approx. 9 hrs? New admin did not work for the bots even once the lobby  was back up.  Thus it is obvious the new code hadn't been tested in the test lobby.

**Comment by DanVanAtta** [comment]
Thanks, water under the bridge @prastle; respect for the efforts to get the lobby to be available again.

The best we can do is to analyze events and do all that we can to prevent and/or lessen the severity of this problem.

One problem was no clear escalation/communication plan, no clear "this is what you do". I think it's pretty clear we need a disaster recovery plan, for follow-up: https://github.com/triplea-game/triplea/issues/3417). I think the DR plan will also make for a better escalation, so we can get the word out sooner that things are going wrong.

As part of having plans, I'm not confident all of the admins/devs can do a restore from scratch, I've created this task for us to do a first round of practice doing disaster recovery: https://github.com/triplea-game/triplea/issues/3420

Another clear problem, the instructions of how to log in and check things were not clearly documented. We should not rely on a dev to reverse engineer our infrastructure code to know how to log in, we need some clear steps (a checklist perhaps), so we can save time and get the job done.. For follow-up here I'd like us to create/finish a proper how-to-admin document (https://github.com/triplea-game/triplea/issues/3418) That would then be the go-to place for how to do the things you were looking to do, and @prastle  would not have needed to rely on me eventually telling him about the updates or waiting for @RoiEXLab to come online to do the reverse engineering (time consuming compared to having a checklist).

Third item, let's say we were not able to log in to the lobby server at all. In that case I would have tried to deploy a new stack on a new server. In that case we are missing backups of the DB, not only would they be stored on the same server as previously configured when we had the Derby Db, but also currently we do not have any automated backup of database data. For follow-up: https://github.com/triplea-game/triplea/issues/3419

Things that likely would not help:
- documenting how to set up a new stack if it came to that. The infrastructure scripts are meant to replace documentation. It may still be valuable to have something to reference the key locations and updates that would be required. I think we'll explore this more plenty when we practice DR: https://github.com/triplea-game/triplea/issues/3420
- more root access. The server was not listening to the IPv4 address, no ssh command was going to work unless you went to linode to check the IPv6 address. 

----------------------

w.r.t the scripts, they are actually of lower priority as they are convenience wrappers. You can still log in via root using password + linode console and run the service scripts directly against `systemctl`. Regardless, they should be working, and the fact we had not practiced/agreed on that, is bad. To be fair we have come a long way from nothing, so I don't think anyone necessarily discounts that either. I don't want to make excuses for breaking a process and creating a new one and not properly training you @prastle  on it, that was a mistake of mine, I bear responsibility for that, I apologize to you once more for that. I expect with a good DR document we'll have practiced it, such kinks would work themselves out.

**Pull request closed without merging**
