### PR TITLE
Use Unified subdomain

### PR DESCRIPTION
**Pull request by RoiEXLab**
Follow up to #165

### CODE REVIEW

**Comment by DanVanAtta** [comment]
I would like to avoid the "lobby-staging.triplea-game.org" going forward.
- The server hosts more than just lobby
- We do not have a 'lobby-prod' for any symmetry
- The hostname is prerelease, it is a bit confusing to have a different domain compared to what we have in the configuration.

**Comment by DanVanAtta** [comment]
It seems I needed to update an IPv6 entry. Our previous prerelease entry was incorrect, unless strong objection let's keep the naming consistent.

**Comment by RoiEXLab** [comment]
@DanVanAtta We should have a single subdomain for the pre-release server that contains a valid A as well as an AAAA entry.
I honestly don't really care how we name it, it should be unified though.

**Comment by DanVanAtta** [comment]
Agree, my 2 cents: let's name it 'prerelease' for consistency with host naming.

**Comment by RoiEXLab** [comment]
Closing via https://github.com/triplea-game/triplea/pull/4506#discussion_r245406594

**Pull request closed without merging**
